spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://taf-db.mysql.database.azure.com:3306/tafdb
    username: mhilali
    password: P@ssword
  jpa:
    hibernate:
      ddl-auto: validate
  thymeleaf:
    suffix: .html
    cache: false
  messages:
    basename: validation
    encoding: ISO-8859-1
    

  
