spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taf-db
    username: mhilali
    password: P@ssword
  jpa:
    hibernate:
      ddl-auto: create
      dialect : ${spring.jpa.properties.hibernate.dialect}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: validation
    encoding: ISO-8859-1
    

  
